# Generated by Django 5.0 on 2024-12-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='medal',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
